### ISSUE TITLE
Thumbnail preview API

### ISSUE THREAD

**Issue by doublex** [fluid-player/fluid-player#448] opened 2020-05-20 14:25 UTC
Gratulation for releasing v3. Beautiful player.
A question. We can't use VTT for some reasons. Is there a chance to extend the preview-thumbnail-API, e.g.:
````
fluidPlayer(
    'my-video',
    {
        layoutControls: {
            timelinePreview: {
                type: 'attached',
                frames: [
                    {
                        start: 0,
                        end: 1000,
                        thumbnail: "http://domain.com/demo/240p-00001.jpg",
                        x: 0,
                        y: 0,
                        w: 320,
                        h: 240
                    },
                    //...
                ]
            }
        }
    }
);
````

**Comment by Addvilz** [comment] 2020-05-20 14:41
Can you provide more information about what is actually the issue with VTT?

There is currently no plan to extend the API to provide previews and it would be a pretty significant change.

**Comment by doublex** [comment] 2020-05-20 15:00
Actually it's not a significant change.
Maybe 5 lines of code.

The format of the frame-array  would be:
https://github.com/fluid-player/fluid-player/blob/master/src/modules/timeline.js#L53
````
[{
    startTime: 1,
    endTime: 2,
    image: '',
    x: 0,
    y: 0,
    w: 320,
    h: 240
},
...]
````

Patch:
````
*** timeline.old        2020-05-20 16:55:10.186129975 +0200
--- timeline.js 2020-05-20 16:57:24.101716757 +0200
*************** export default function (playerInstance,
*** 192,197 ****
--- 192,200 ----
                      window.WebVTTParser = it.default;
                      playerInstance.setupThumbnailPreviewVtt();
                  });
+             } else if (playerInstance.displayOptions.layoutControls.timelinePreview.type === 'inline' &&
+                         playerInstance.displayOptions.layoutControls.timelinePreview.frames ) {
+                 playerInstance.timelinePreviewData = playerInstance.displayOptions.layoutControls.timelinePreview.frames;
              }
  
              playerInstance.showTimeOnHover = false;
````

**Comment by Addvilz** [comment] 2020-05-20 15:05
It's not just about code, it's about introducing and supporting a duplicate of already existing feature and all that comes with it.

Thus me asking, what is the actual issue with VTT?

**Comment by doublex** [comment] 2020-05-20 15:53
It runs 100% on the client side.
We could create a VTT on the client - but how to pass this VTT over to the player?

**Comment by Addvilz** [comment] 2020-05-20 16:13
I am not sure generating VTT in client side is a good idea. Why not generate VTT at the same time VTT image sprite is generated and have it as an external file?

**Comment by doublex** [comment] 2020-05-20 16:25
This would cause us a lot of grief.
Don't worry. Either we stick to our current solution or we will patch fluid-player on each release.

**Comment by Addvilz** [comment] 2020-05-20 16:31
Alright. However, if you do want to implement this - you are welcome to submit a PR. However, the above patch would not be acceptable - you would need to implement another timeline preview type, `timeline.js#L170` and the whole timeline.js would need to be refactored to support that.

**Comment by doublex** [comment] 2020-05-20 16:35
Thanks, I will create a pull request.

**Comment by doublex** [comment] 2020-05-20 16:51
Would you accept something similar to this?
https://github.com/doublex/fluid-player/commit/48e7974b7d3d2f008d33a39b0b30b837453bf305

The API would be like:
````
fluidPlayer(
    video_element,
    {
        layoutControls: {
            timelinePreview: {
                type: 'static',
                frames: [
                    {
                        startTime: 0,
                        endTime: 500,
                        image: 'https://domain.com/path/to/image.jpg',
                        x: 0,
                        y: 0,
                        w: 320,
                        h: 240
                    },
                    // next frame ...
                ]
            }
        }
    }
);
````

**Comment by Addvilz** [comment] 2020-05-20 18:34
The API part looks fine to me. But the timeline.js will need a lot more work - it needs to be refactored completely to not duplicate any code already there related to thumbnail rendering etc. VTT specific code needs to be split apart (though in the same file probably) from rendering.

**Comment by doublex** [comment] 2020-05-20 19:36
Refactoring timeline.js?
Why not simply copy the configuration to `playerInstance.timelinePreviewData`?
Just an idea:
https://github.com/doublex/fluid-player/commit/48e7974b7d3d2f008d33a39b0b30b837453bf305

**Comment by Addvilz** [comment] 2020-05-20 20:41
Did you test the change? Does it actually work?

Besides that, our current policy has changed - from V3 onwards we will continuously work on improving the codebase to clean up all the legacy we have. timeline.js is one such legacy - once you touch it, you will be required to refactor it. :)

**Comment by doublex** [comment] 2020-05-21 10:25
It is untested.
My question: Will you accept a patch like the above if I provide a demo?
I want a good-looking and lightweight player - not refactoring timeline.js.

**Comment by Addvilz** [comment] 2020-05-21 10:42
Please understand that the changes you do and contribute will have to be maintained by Fluid Player members. IF you need this feature, we are open to a pull request from you, but this case is not like fixing a one-liner bug. It's a new feature, it requires documentation and it **has to** adhere to our code quality minimum.

The only way I see you can introduce this feature is refactor of timeline.js - split apart loading of preview and rendering it, so rendering can be re-used between VTT and "static" type - as the bare minimum.

Also consider that we want this code to be eventually testable. The whole goal of V3 release is to take a first step in that direction.

> I want a good-looking and lightweight player - not refactoring timeline.js.
One will not happen without another. There is a lot of scaffolding and unnecessary code in the player now. Just hacking around it will make the player even more bloated than it already is, and we can't have that.

**Comment by doublex** [comment] 2020-05-21 12:38
Thanks a lot for your help.

**Closed** 2020-05-29 10:12 UTC
Labels: enhancement, feature request

**Comment by Addvilz** [comment] 2020-05-29 10:29
Published with the latest release.

**Comment by doublex** [comment] 2020-05-29 10:37
Thanks a lot!
fluid-player is the best video-player (I have tried them all)
