### ISSUE TITLE
Lighthouse says: Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by Lestadt** [fluid-player/fluid-player#404] opened 2019-11-25 16:47 UTC
Hello, apparently everything works fine with the player, however when auditing my site with the Lighthouse tool it shows me this error or suggestion:

  Does not use passive listeners to improve scrolling performance
https://cdn.fluidplayer.com/v2/current/fluidplayer.min.js

I am trying to optimize my site, basically to accelerate the load on mobile devices and this error is something that I must solve, I don't know if you should update the fluidplayer.min.js file or if there is something that I can do on my own to Solve this, I would appreciate any suggestions.

**Comment by HariPriyaKuberSingh** [comment] 2021-11-30 12:51
@Lestadt - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 10:59
@Lestadt - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment] 2022-01-05 10:35
Closing the ticket since there is no confirmation from the reporter

**Comment by biguz** [comment] 2023-08-02 11:08
Still not resolved https://pagespeed.web.dev/analysis/https-www-fluidplayer-com/c6eg5xjgg6?hl=en&form_factor=mobile

**Comment by leroybm** [comment] 2023-08-02 14:38
Reopening, adding the passive flag should fix this.

**Comment by leroybm** [comment] 2023-08-31 10:33
@biguz @Lestadt The fix for this was just released. Can any of you confirm that this is fixed so I can close the issue?

**Comment by leroybm** [comment] 2023-09-12 17:14
@biguz @Lestadt Can you close this if it's ok?

**Comment by leroybm** [comment] 2023-09-25 09:08
Closing this ticket since the issue is resolved

**Closed by leroybm** 2023-09-25 09:09 UTC
Labels: enhancement
