### ISSUE TITLE
Show quality selector with HLS stream

### ISSUE THREAD

**Issue by entrailz** [fluid-player/fluid-player#197] opened 2018-06-01 02:33 UTC
Hey,

Is it possible to get a quality selector on HLS streams? For example, I have a stream that is in 720p and 288p, I would like the user to be able to choose between them.

Thanks!

**Comment by cian-exads** [comment] 2018-06-12 09:37
Hi @entrailz, the purpose of HLS and other streaming protocols is that the quality is on-demand. The file itself contains the links to all the different qualities and the correct one is selected based on the clients bandwidth. I believe this would be the most correct way to have multiple qualities available. Having said that if you set more than one HLS source file in your <video> tag I believe it will allow the client to switch between. Closing this ticket as there is no development work required.

**Closed by cian-exads** 2018-06-12 09:37 UTC
Labels: question

**Comment by derblub** [comment] 2019-03-07 14:50
Sorry for reviving this old thread, but switching the source of a hls-stream is a valid use case and there is user-demand for exactly this feature.  
Check YouTube for example. It's player is default always on the `auto`-quality option since quite some time already, but you can always switch the source manually. They never disabled this feature, because users are using it. If the user knows about his bad bandwidth and still wants to watch that file in 4k, knowing it will take ages to load - why stop him doing so?  

Please revise, since in my current project, the `m3u8`'s are coming from an external source and they do not provide separated streams.

**Comment by cedricbdev** [comment] 2019-05-31 09:19
I have long searched for this feature and I have never found an answer. The only solution I have found for now is to analyze the content of the m3u8 file and then retrieve all the sources of the different resolutions with this regex I made: /RESOLUTION=\d+x(\d++),?.*\s(.+\.m3u8(\?.++)??)/mU
Then I transform the single <source> tag containing the original m3u8 by a set of <source> tags each containing the file in each resolution detected with the regex.

WPS Player from WP-Script uses this technique to provide the resolution switcher with m3u8.

**Comment by Barahten** [comment] 2020-04-24 10:36
@cradonn, Hi, сan you show here how you implemented it? I think it will be very interesting to many

**Comment by Addvilz** [comment] 2020-04-24 10:48
As I mentioned in #437 there is a possibility to implement this, hls.js has an API for manual quality switching - https://github.com/video-dev/hls.js/blob/master/docs/API.md#quality-switch-control-api 

The problem is, there is currently no integration between quality switcher in fluid-player and HLS api, and there is no obvious way for you to deal with that except for using outside quality switcher and separate m3u8 files - one per each "preferred" quality.

**Comment by Barahten** [comment] 2020-04-24 10:53
@Addvilz Hi
I understand that his way (@cradonn ) is to parse the manifest, create a `source` tag inside the `video` tag and then call the fluid player

**Comment by Addvilz** [comment] 2020-04-24 11:02
That is provided you have 1 (!!!) file per each quality, not a set of chunks. If that is the case, you don't need to use HLS at all, beats the purpose of it - just have multiple <source> tags outright. If however the stream is chunked, the above will not work.

**Comment by Barahten** [comment] 2020-04-24 11:06
That is, do you propose to parse a manifest, for example on PHP, generate a `video` tag with all `source` tags and subtitles, and then call the fluid-player?

**Comment by Addvilz** [comment] 2020-04-24 11:08
Again, depends on the manifest. If the manifest contains multiple chunks per quality (ex. adaptive quality - https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/video_on_demand_playlist_construction) then what you propose will not work.

**Comment by Barahten** [comment] 2020-04-24 11:13
No, I’m not such a playlist: I have one m3u8 master playlist, which has links to other m3u8 playlists, which connect depending on the network bandwidth. For example
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=305800,RESOLUTION=426x240,CODECS="avc1.640015,mp4a.40.2"
res-0/playlist.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=444400,RESOLUTION=640x360,CODECS="avc1.64001e,mp4a.40.2"
res-1/playlist.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=965800,RESOLUTION=854x480,CODECS="avc1.64001e,mp4a.40.2"
res-2/playlist.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=1267200,RESOLUTION=1280x720,CODECS="avc1.64001f,mp4a.40.2"
res-3/playlist.m3u8
```

**Comment by Addvilz** [comment] 2020-04-24 11:16
And what are the contents of `res-0/playlist.m3u8`?

**Comment by Barahten** [comment] 2020-04-24 11:17
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:6.000000,
//content.vidi.one/storage/KNBj6ewf/res-0/segment-0.ts
#EXTINF:6.000000,
//content.vidi.one/storage/KNBj6ewf/res-0/segment-1.ts
#EXTINF:1.480000,
//content.vidi.one/storage/KNBj6ewf/res-0/segment-2.ts
#EXT-X-ENDLIST
```

**Comment by Addvilz** [comment] 2020-04-24 11:20
Ok, so above approach will not work for you. At this time there is no way for you do force the quality except for having multiple m3u8 files with separate qualities and switching between them outside player itself.

**Comment by Barahten** [comment] 2020-04-24 11:26
Why?
Can't I parse the master playlist to php and generate html like below
```
<video>
	<source src="res-0/playlist.m3u8" title="240" type="application/x-mpegURL" />
	<source src="res-1/playlist.m3u8" title="480" type="application/x-mpegURL" />
	<source src="res-2/playlist.m3u8" title="720" type="application/x-mpegURL" />
</video>
```
and then connect the player?

**Comment by Addvilz** [comment] 2020-04-24 11:27
Try to do this manually and see if it works. But I am fairly certain you can't do it this way.

**Comment by Barahten** [comment] 2020-04-24 12:24
I tried and it works. Not perfect, of course, but it still works.

**Comment by inside83** [comment] 2021-01-22 05:46
> I tried and it works. Not perfect, of course, but it still works.

I tried it too and while it does work, it defeats the purpose of a master playlist
