### ISSUE TITLE
controlBar: { autoHide:false

### ISSUE THREAD

**Issue by ERI123** [fluid-player/fluid-player#82] opened 2018-02-15 15:50 UTC
Hello
New code 
controlBar: {
                 autoHide: false,
},
Do not work.

Only when I add.
<style>
.fluid_video_wrapper.fluid_player_layout_default .fluid_controls_container {
    visibility: visible;!important;
    opacity: 1;!important;
}
</style>

**Comment by Danny15** [comment] 2018-02-16 09:12
Hi @ERI123 , If you want the control bar to hide after 3 seconds then you need to apply: 
controlBar: {autoHide: true}. If this is applied with your custom code the the controls will display when player loads and the control bar will autohide after 3 seconds. I just tested and this works.

If your intended behavior is to always show the control bar then your custom code will work and there is no need to apply the autoHide option. 

Could you give us further information regarding your intended behavior?

**Comment by ERI123** [comment] 2018-02-16 12:58
but also on main site https://www.fluidplayer.com/ they use this
<style> .fluid_video_wrapper.fluid_player_layout_default .fluid_controls_container { visibility: visible;!important; opacity: 1;!important; } </style> 
to not auto hide the controlbar.

**Comment by Danny15** [comment] 2018-02-16 16:29
Hi @ERI123, I understand that you want the controls to always display but not apply the custom CSS. The autoHide option does not function as a way to 'always show controls'. It only works to apply the auto hiding feature for the control bar after a number of seconds. Setting to false simply turns this auto-hiding off.  What you require is not available with this feature. 

I will pass this case to our main development team and we will consider it in future development.

**Comment by cian-exads** [comment] 2018-05-23 16:28
@ERI123, we agreed that the controls should show as seen fluidplayer.com. In V2 of Fluid Player we put in a fix so that the controls show when the video isn't playing, regardless of **controlBar** settings. Closing this issue.

**Closed by cian-exads** 2018-05-23 16:28 UTC
Labels: help wanted
