### ISSUE TITLE
Setting VAST after initializing FluidPlayer

### ISSUE THREAD

**Issue by sinni800** [fluid-player/fluid-player#529] opened 2020-09-30 21:30 UTC
We've upgraded Fluidplayer to 3.0 and now my solution detailed in https://github.com/fluid-player/fluid-player/issues/173 does not work anymore because the displayOptions (or layoutControls) are not available in the fluidplayer object anymore. What it has is this, and none of these options can help me set up VAST after the fact anymore:

```
document.fplayer

dashInstance: function dashInstance()​
destroy: function destroy()​
hlsInstance: function hlsInstance()​
on: function on(t, n)​
pause: function pause()​
play: function play()​
setHtmlOnPauseBlock: function setHtmlOnPauseBlock(t)​
setPlaybackSpeed: function setPlaybackSpeed(t)​
setVolume: function setVolume(t)​
skipTo: function skipTo(t)​
toggleControlBar: function toggleControlBar(t)​
toggleFullScreen: function toggleFullScreen(t)
```

**To Reproduce**
After fluidplayer is initialized:

```
        document.fplayer = fluidPlayer(
		"myVideoPlayer",
		{ 
			layoutControls: {
				layout: "default"
			}
		}
	)
```

My advertisement script runs and also emits this javascript:

```
    document.fplayer.displayOptions.vastOptions.adList = {
        "some_ad": {
            roll: "preRoll", 
            vastTag: "https://some/vast.xml"
        }
    };
    document.fplayer.setVastList();
```

Expected behaviour: `displayOptions` in the fluidplayer object exists and lets me set these. `setVastList()` exists.

Affected Version: 3.0.4 (I don't know how many before that)

If there's a new way to do this now, that would be great also.

**Comment by Addvilz** [comment] 2020-10-01 06:40
The reason why the API you ask about is no longer available is because it is a private API and it should not have been available in the first place it's an internal API, and doing what you do - modify it after the initialization is not supported.

I am a bit skeptical about if your modification worked in the first place, since VAST would expect to be present on media start, not some time after the fact.

Is there a reason why you can't create the VAST options before the player is initialized?

**Comment by sinni800** [comment] 2020-10-10 00:21
I've ended up just pulling them from the ad script in a different way, fusing the objects and then initializing it all at once... But now, I've encountered some other bug that I should probably make another issue for. The VAST doesn't initialize a skip button anymore in the new version we updated to...

**Comment by Addvilz** [comment] 2020-10-18 13:17
Is the skip offset present in the VAST config?

**Comment by sinni800** [comment] 2021-01-15 02:57
It was present. We since switched to another ad network where it works fine...

**Comment by HariPriyaKuberSingh** [comment] 2021-12-01 13:00
@sinni800 - From your above comments I can conclude that the issue was resolved . Can you please cofirm if we could close the ticket or does the issue require any additional attention?

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 11:18
@sinni800 - From your above comments I can conclude that the issue was resolved . Can you please cofirm if we could close the ticket or does the issue require any additional attention?

**Comment by sinni800** [comment] 2021-12-25 05:23
Yes, this issue was an issue of the VAST description of the AD network at the time, it isn't really a problem anymore.

**Comment by HariPriyaKuberSingh** [comment] 2022-01-18 09:45
Based on the above comments from the reporter,the issue is fixed and hence closing the ticket

**Closed by HariPriyaKuberSingh** 2022-01-18 09:45 UTC
Labels: feature request, needs triage
