### ISSUE TITLE
Setting the VAST url after initializing FluidPlayer

### ISSUE THREAD

**Issue by sinni800** [fluid-player/fluid-player#173] opened 2018-05-23 19:02 UTC
I'm trying to set the VAST url after setting up FluidPlayer. This is so I can use Fluid Player as my regular HTML5 webm player but also outfit it with ads down the line if the user in question is eligible to see ads. 

I have tried this to accomplish 

```
document.fplayer = fluidPlayer(
		"gelcomVideoPlayer",
		{ 
			layoutControls: {
				layout: "default"
			}
		}
	)
```

Then, when an ad is supposed to be shown: 

```
    document.fplayer.displayOptions.vastOptions.adList = {
        "lel": {
            roll: "preRoll", 
            vastTag: "https://some/vast.xml"
        }
    };
    document.fplayer.setVastList();
```

This results in the ad playing at preRoll, but in an unlimited loop!

Is there a way to solve this?

**Comment by cian-exads** [comment] 2018-05-24 10:13
Hi @sinni800, I've tested locally using your fix and it works correctly for me. I hadn't thought to use **.setVastList()** after initialisation to set VAST dynamically, really interesting approach!
Can you link me a test page where I can see this happening, and hopefully we'll be able to solve this issue.

**Comment by sinni800** [comment] 2018-05-24 20:33
Our dev server is not really accessible from outside, so I don't know how to proceed with a usable example.

The VAST server is currently not even sending the VAST xml correctly as `application/xml` but rather as `text/html`, which breaks VAST support. I'm using a hack to force parsing it as XML during development, see https://github.com/fluid-player/fluid-player/issues/162 

I would share the concrete VAST url and my code example in private, though

**Comment by cian-exads** [comment] 2018-05-25 09:22
Sure thing @sinni800, you can email me at cian@exads.com and we can take a deeper look into this.

**Comment by sinni800** [comment] 2018-06-03 23:07
Turns out that adding "loop" to the html5 video tag will make the AD loop too!

Current workaround: 

`        document.fplayer.displayOptions.vastOptions.vastAdvanced = {
            vastLoadedCallback:       (function() { document.gplayer.loop = false;  }),
            noVastVideoCallback:      (function() { document.gplayer.loop = true; }),
            vastVideoSkippedCallback: (function() { document.gplayer.loop = true; }),
            vastVideoEndedCallback:   (function() { document.gplayer.loop = true; })
        };`

**Comment by cian-exads** [comment] 2018-06-12 09:00
Hey @sinni800, good to see ye got to the cause of this! Going to close this ticket.

**Closed by cian-exads** 2018-06-12 09:00 UTC
Labels: help wanted

**Comment by sinni800** [comment] 2018-06-12 11:59
@cian-exads Would it a good idea to make another issue for that the ads loop when the "loop" value of the player is set? My current workaround works, but I don't think it's ideal

**Comment by cian-exads** [comment] 2018-06-12 12:04
There's a PR to do just that @sinni800, hopefully it will be part of the next release. Here's the PR - https://github.com/fluid-player/fluid-player/pull/214/files

**Comment by sinni800** [comment] 2018-06-12 12:05
Oh, cool, I haven't seen that @cian-exads ! I am still not very fluent at successfully navigating Github :)
