### ISSUE TITLE
In Full Screen Fluid Player Crops the video

### ISSUE THREAD

**Issue by jessica-bc** [fluid-player/fluid-player#459] opened 2020-05-28 21:03 UTC
I have been using fluid player since 3 months now, Its awesome player and the good thing is its absolutely free. Loved it!!
There is an issue with one of my website, my HLS videos are cropped only when website is accessed through mobile. Desktop version works fine in full screen, but when it comes to mobile full screen it crops the video consequently hard coded video subtitles are invisible in full screen. 
HELP REQUIRED!!

For reference please visit this link via mobile and use the full screen.
https://8maple.su/2103

**Comment by Addvilz** [comment] 2020-05-29 09:45
Please provide more information - mobile: what operating system, device version? Which Fluid Player version? Can you provide screenshots/photos something that illustrates what you consider cropped?

**Comment by jessica-bc** [comment] 2020-05-29 11:10
Thankyou for coming back at me. Refer to the following images for more information.

https://ibb.co/hXKpxZc
https://ibb.co/F3RX6PN
https://ibb.co/cx9d07c

1. Image has android specification
2. Image taken when in non-fullscreen mode
3. Image taken at same instance in fullscreen mode.

Which clearly shows that video has been cropped. Another issu worth mentioning here is, when I go in full screen player always shows at the top and controls at the bottom as clear in the following image.
https://ibb.co/mNXvKL7

Thats how I declare it in my posts. Am I doing something wrong here?
`<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<video id="video-id"> <source src=" " type="application/x-mpegURL" />
</video>

<script>
fluidPlayer(
   'video-id',
    {
        layoutControls: {
            primaryColor:          "#28B8ED",
           fillToContainer:        true, 
   controlBar: {
                autoHide:           true,
                autoHideTimeout:    3,
                animated:           true
            }         
        }
    }
);
</script>`

**Comment by Addvilz** [comment] 2020-05-29 11:19
These seem like styling/sizing issues in the player itself. I don't think this particular part of Fluid Player has been tested that well.

We will look into that.

**Comment by jessica-bc** [comment] 2020-05-29 18:05
Thankyou.. will be waiting for update.. Anything which can be done to avoid this at the moment?

**Comment by Addvilz** [comment] 2020-06-11 15:28
@jessica-bc after some further testing, I am able to reproduce the toolbar problem, but not the problem with styling.

I can't also reproduce the issue on your site since there are CORS issues and the playlist does not work for the link you provided.

While testing locally, nothing is cropped or cut, the video appears on the middle of the screen or is fit to screen on fullscreen.

This leads me to believe there is an issue with CSS on your site that affect the player.

**Comment by Addvilz** [comment] 2020-06-11 15:49
A local reference test is available at autohide-test branch of the repository, part of refactor PR #472. @jessica-bc you can use it to verify whether or not you can reproduce the issue with the crop and control bar using reference code. You will need `yarn` for that, use command `yarn dev-server` at the root of the repo on said branch. Head to `<LAN IP>:8080/vod_basic_autohide.html` to see the reference test code.

**Comment by jessica-bc** [comment] 2020-06-17 14:51
> @jessica-bc after some further testing, I am not able to reproduce the toolbar problem or the problem with styling.
> 
> I can't also reproduce the issue on your site since there are CORS issues and the playlist does not work for the link you provided.
> While testing locally, nothing is cropped or cut, the video appears on the middle of the screen or is fit to screen on full-screen.
> 
> This leads me to believe there is an issue with CSS on your site that affect the player.
> 
> I can't reproduce the issue with control bar on my device either. It only appears (and stays visible) when paused - just like in your screenshot. That is an expected behaviour.
> 
> See screenshots bellow
> 
> https://ibb.co/MkcJXhk
> https://ibb.co/CMRJrv7
> https://ibb.co/YNSYTHk
> https://ibb.co/PckRT10

Toolbar works ok, I only have problem with video being cropped. and in full screen video goes to the top, no in center when mobile is in portrait mode. That is also not a big issue.
The only thing which is really bothering is video being cropped in full screen landscape mode in mobile ONLY.
For further reference [Visit here](https://8maple.su/4503)

In mini screen video displays hard coded subtitles in video perfectly. But in full screen these subtitles are cropped from the video.

**Comment by jessica-bc** [comment] 2020-06-17 14:52
> A local reference test is available at autohide-test branch of the repository, part of refactor PR #472. @jessica-bc you can use it to verify whether or not you can reproduce the issue with the crop and control bar using reference code. You will need `yarn` for that, use command `yarn dev-server` at the root of the repo on said branch. Head to `<LAN IP>:8080/vod_basic_autohide.html` to see the reference test code.

I'd have done it if I was able to. Im no pro, and could not grasp what you said. Letme know how could I be of any help.

**Comment by jessica-bc** [comment] 2020-06-18 10:07
> I can not test using the link you provided - following error prevents video media from loading.
> 
> `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://youku.cdn2-okzy.com/20200617/10101_b0d29eec/1000k/hls/index.m3u8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`
> 
> Once you fix this, I can take another look. However, I can already see some custom CSS being applied to the player video element, so that might be whats causing this and why I can not reproduce this issue using our reference test code.

I have allowed cross origin requests. You can test it now.. Anxiously waiting for it to be resolved!!

**Comment by Addvilz** [comment] 2020-06-22 08:35
@jessica-bc still does not work for me. I now get 403 error on the original M3U8 file. Do you have any geographic restrictions for the file access?

```
403 Forbidden
denied by request access control
```

```
HTTP/2 403 Forbidden
server: kangle/3.5.20.4
date: Mon, 22 Jun 2020 08:29:59 GMT
content-type: text/html; charset=utf-8
x-cache: MISS from dy1-23
content-length: 973
X-Firefox-Spdy: h2
```

**Comment by Addvilz** [comment] 2020-06-22 13:14
To get this going, I was able to temporarily replace the video element in your site with test code referencing another video file.

The issue you are facing is not related to Fluid Player - you have custom CSS in your site that breaks Fluid Player styling.

For example, this piece - 

```
img, video, object {
    max-width: 100%;
    height: auto !important;
}
```
height property here breaks the alignment of the video in fullscreen mode. I suspect max-width is also not necessary.

Since this issue is not related to Fluid Player, I will close this issue. 

In unrelated note, you are still using `2.4.11` - v2 is end of life and will receive no further updates. Please upgrade to the latest v3 version, currently `3.0.2` - it incorporates many improvements and bugfixes.

**Closed by Addvilz** 2020-06-22 13:14 UTC
Labels: bug, need more info, needs triage

**Comment by jessica-bc** [comment] 2020-06-22 21:13
Thankyouu soooo Muchhh Mr @Addvilz .. I cant tell how much Im happy and thankful to you for investing your precious time in my problem. you are a savior. You were totally right this piece of code was messing with the video. After removing this, Video now works like charm. Thanks a ton!! 
Loving fluid player even more. More power and progress to you!!!

**Comment by Addvilz** [comment] 2020-06-22 22:02
No problem at all. 

I don't think you can, but redesigning the controls and behavior for mobile is something we are considering for future. There are quite a backlog of things that we need to look into.

**Comment by jessica-bc** [comment] 2020-06-28 19:09
Yes I would like to point out another issue at the moment for mobile (Dont know if I should create new post here). Which is related to logo setting for the player, when we set the custom logo it does not hide with the controls despite using  hideWithControls: true,   works perfectly fine for desktop but not for mobile(android with same specification above). and I wanna know if there is anyway to show the logo despite the control go hidden. For branding purpose so that the brand icon ramains at the top when video is playing. Is it possible? Or please consider is in new update.

**Comment by Addvilz** [comment] 2020-06-29 06:16
With hideWithControls = true, the logo should hide with controls - and opposite, false should not hide the logo with controls. So for logo to be shown permanently you should set hideWithControls = false.

https://docs.fluidplayer.com/docs/configuration/layout/#logo

I created a separate bug #485 to see about what's going on with Android.

**Comment by jessica-bc** [comment] 2020-07-08 14:18
But doing this hideWithControls = false also stop the controls from being hidden. Which in turn interferes with subs. 
So my suggestion would be there should be using this command hideWithControls = false should not interfere controls setting also. So that controls can hide according to the timeout we set. As this command is hideWithControls = false only for logo not controls as well.

**Comment by Addvilz** [comment] 2020-07-08 14:25
I am sorry, I do not follow - when controls hide and hideWithControls = true, the logo is show only when controls are shown. When hideWithControls = false, logo is shown always. hideWithControls does not affect how controls are hidden.

**Comment by jessica-bc** [comment] 2020-12-03 09:56
My suggestion was, there should be an option to show the logo always without controls. If possible in next update!

**Comment by Izian4321** [comment] 2020-12-06 17:16
Hwlo
