### ISSUE TITLE
Causes issues on mobile

### ISSUE THREAD

**Issue by ravikiranp123** [fluid-player/fluid-player#595] opened 2021-07-15 09:46 UTC
https://github.com/fluid-player/fluid-player/blob/ba6253869ecebd2cde97ab608bce6749ac574cc5/src/fluidplayer.js#L1888

Hello! I recently noticed that the above line causes issues on mobile. Throws error: "Uncaught TypeError: Cannot read property 'clientWidth' of null"

The video just stays blank. Everything used to work fine before though. I am looking for help.

Thanks!

**Comment by konyilwin** [comment] 2022-01-05 13:39
Same here

**Comment by Mersal-Mohamed** [comment] 2022-04-18 00:19
same here

**Comment by kyimoemin** [comment] 2023-02-03 11:17
is there any workaround? I got the same error

**Comment by SpunToFuck** [comment] 2023-02-03 22:12
Same here......BUT I AM VERY MUCH INTERESTED IN CHATTING & TALKING TO ANY ONE ANYWHERE FOR 💕💖😘 SEXTING, LOVE-TALK & ANYTHING ELSE YOU WANNA DO💕😍😍😍😍contact me ASAP IFS YOU'RE INTERESTED💋💋💋💋

**Comment by leroybm** [comment] 2023-09-06 14:54
@ravikiranp123 @konyilwin @snuffy @ppiwo @Mersal-Mohamed @kyimoemin, is this still an issue? I could not reproduce this on my side. Can any of you share your configs?

**Comment by ppiwo** [comment] 2023-09-06 15:59
> @ravikiranp123 @konyilwin @snuffy @ppiwo @Mersal-Mohamed @kyimoemin, is this still an issue? I could not reproduce this on my side. Can any of you share your configs?

I don’t have access anymore, sorry!

**Comment by konyilwin** [comment] 2023-09-06 16:08
I will test again later and ping you.

**Comment by leroybm** [comment] 2023-09-08 08:59
@konyilwin have you had time do test this?

**Comment by sergiomcsousa** [comment] 2024-02-26 10:30
@konyilwin @Mersal-Mohamed @ravikiranp123 is this still an issue? Can I close this? Thank you!

**Comment by sergiomcsousa** [comment] 2024-02-27 15:30
Closing the ticket due to a lack of feedback over an extended period. Please feel free to reopen if you have further input or require additional assistance. Thank you.

**Closed by sergiomcsousa** 2024-02-27 15:30 UTC
