### ISSUE TITLE
Google Chromecast

### ISSUE THREAD

**Issue by mannanzinat** [fluid-player/fluid-player#402] opened 2019-11-23 13:17 UTC
Dear Sir,
Do you have any plan to add google chromecast support?? I am using videojs player now on a video cms which is live more than 500+ websites now.if you add chromecast then I'll switch to fluidplayer.

Thanks

**Comment by Addvilz** [comment] 2020-05-20 13:46
Duplicate of #265

**Closed by Addvilz** 2020-05-20 13:46 UTC
Labels: feature request, needs triage
