### ISSUE TITLE
Set default source

### ISSUE THREAD

**Issue by EhsanCh** [fluid-player/fluid-player#278] opened 2018-10-08 10:20 UTC
Hello
Is there an official way to set default video source ? currently it is first source !
a data-fluid-isdefault attribute is a good option. also a setSource() function is appropriate .

Regards

**Comment by cian-exads** [comment] 2018-10-09 08:59
Hi @EhsanCh, at the moment there's no official way to do this. But we have persistent settings for the quality so that once the quality has been change it will be remembered on page reload / change.  https://docs.fluidplayer.com/layout_configuration/#persistentsettings

Unofficially there's a `myPlayerEle.setVideoSource(url)` function that will change the source, but it won't correctly highlight the button selected. This is the same for the standard [video source switch](https://stackoverflow.com/questions/5235145/changing-source-on-html5-video-tag). Or you could create a [custom click function](https://stackoverflow.com/questions/6431891/select-an-element-by-title-in-jquery) on the buttons based on their titles.

I think adding a `setSource()` function makes sense to have, and I'll mention it to be considered in future development.

**Comment by HariPriyaKuberSingh** [comment] 2021-11-30 12:34
@EhsanCh  - Hi, Does the issues persist ?

**Comment by HariPriyaKuberSingh** [comment] 2021-12-16 15:03
@EhsanCh - Can you please confirm if the issues still persist

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 10:01
Closing the ticket as there is no confirmation if the issue is still persisting

**Closed by HariPriyaKuberSingh** 2021-12-24 10:01 UTC
Labels: enhancement
