### ISSUE TITLE
Vast Tag issue with Adblocker 

### ISSUE THREAD

**Issue by jessica-bc** [fluid-player/fluid-player#526] opened 2020-09-23 13:20 UTC
When the ad blocker is on, and vast tags are configured; the moment the ad show up the video and player itself vanishes. Only the background audio continues on playing. Please fix this issue!

This can be seen here https://8maple.su/video/75102

Google Chrome Latest Version
AbBlock Plugin Latest Version

One more thing, Im unable to produce skip button white ad start to run. Please help me in that too if u can. 
Thankyou in anticipation.

**Comment by Addvilz** [comment] 2020-09-23 13:33
Unable to reproduce. Fluid Player is tested with AdBlock, AdBlock Plus and uBlock origin - in all cases, VAST fails to load but with no visible effect on the player itself - which is expected.

I just tested the reference code again and it works just fine with all 3 ad blockers. 

Please, try to reproduce this issue with the reference site - https://docs.fluidplayer.com/docs/configuration/ads/

If it works on the reference site, but not on your page, it is most likely an issue with your page, not the FluidPlayer itself.

**Comment by jessica-bc** [comment] 2020-09-23 13:47
I have m3u8 media file, and vast tags are installed on mid rolls only at instances 25%, 50% and 75%. No pre and post roll is configured.

i.e. check this link at 22:48-22:49. At this instance ad should appear and it appears when adblock is disabled. But when enabled the issue persists. Please help!  I dont know how to find out if its not fluid player related, any hint would be much appreciated.

**Comment by Addvilz** [comment] 2020-09-23 13:55
What is the actual issue then? If you have AdBlock enabled, VAST will not work, that is expected.

**Comment by jessica-bc** [comment] 2020-09-23 14:17
I have edited the above comment accordingly, main issue is again stated below:
When the ad blocker is on, and vast tags are configured; the moment the ad show up the video and player itself vanishes. Only the background audio continues on playing. 
One more thing, Im unable to produce skip button white ad start to run. Please help me in that too if u can.
You people have help me once before, looking forward to it again. Thankyou for your precious time.

**Comment by Addvilz** [comment] 2020-09-23 14:31
I am unable to check your website since you web player does not work for me - m3u8 playlist HTTP response is 403 Forbidden

**Comment by jessica-bc** [comment] 2020-09-28 08:32
Its working now. 
One more query is that why wordpress plugin is not being updated to V3 of fluid player. That plugin keeps loading v2.0.
How can I get rid of that?

**Comment by Addvilz** [comment] 2020-09-28 09:09
You mean the issue is resolved?

The WordPress plugin is pending a complete rewrite. It's a very old plugin that is no longer viable to be updated.

**Comment by Addvilz** [comment] 2020-10-18 13:17
Closing, I don't see anything to do here.

**Closed by Addvilz** 2020-10-18 13:17 UTC
Labels: bug, needs triage

**Comment by jessica-bc** [comment] 2020-12-03 10:15
Im so sorry for this late, I have updated the source so that its accesible. There is a preroll. And to demonstrate the issue I have recorded two videos.
1. Without adblocker (works fine)
2. With adblocker (player vanishes)

1. https://ok.ru/video/2541181799159
2.https://ok.ru/video/2541181733623
