### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by jozef5198** [fluid-player/fluid-player#252] opened 2018-08-05 23:45 UTC
One of main functions is missing in player. Subtitle support.

**Comment by cian-exads** [comment] 2018-08-13 10:03
Hi @jozef5198, subtitle support is in the development pipeline, but I will mention this issue to maybe look to prioritise it.

**Comment by plonknimbuzz** [comment] 2018-08-16 21:14
@cian-exads where we can find it? i browse all non master branch but not find any `subtitle` string in fluidplayer.js, and changelog.md
thanks

**Comment by plonknimbuzz** [comment] 2018-08-17 14:04
owh. i see
i just miss understand your word.
thanks for the clarification. this means alot to me.

**Comment by Media182** [comment] 2018-10-01 11:39
Would be really good to have .VTT support in player.

**Comment by bharath-exads** [comment] 2019-07-12 11:55
#348

We are adding Multiple Subtitles (VTT) support

**Comment by bharath-exads** [comment] 2019-07-12 11:56
Duplicate of #59

**Comment by bharath-exads** [comment] 2019-07-31 16:52
Hi,

Please check our latest release which has support for subtitles

**Closed** 2019-08-02 10:12 UTC
Labels: enhancement

**Comment by Media182** [comment] 2022-05-03 07:59
Subtitles are not working in current version?
Can't see them working on demo page: https://docs.fluidplayer.com/docs/configuration/subtitles/
