### ISSUE TITLE
Is there a way how to add a subtitle?

### ISSUE THREAD

**Issue by irieislaw4** [fluid-player/fluid-player#298] opened 2019-01-12 06:41 UTC
I tried adding a <track> tag inside the <video> tag but it's not showing.

**Comment by bharath-exads** [comment] 2019-07-12 13:02
Duplicate of #59

**Comment by bharath-exads** [comment] 2019-07-31 16:54
Hi,

Please check our latest release
https://docs.fluidplayer.com/subtitles/

**Closed** 2019-08-02 10:17 UTC
Labels: enhancement
