### ISSUE TITLE
How to make subtitle select by default

### ISSUE THREAD

**Issue by SalimF** [fluid-player/fluid-player#681] opened 2022-08-20 21:50 UTC
I installed fluid-player on my website, everything works well but subtitle are not selected by default  
which mean when visitors play the video they won't see the subtitle, very few people will notice the sub change button .
 

**Additional context**
![image](https://user-images.githubusercontent.com/16048674/185767133-c7cd5e50-0ec1-4c29-bdc1-5aea24c2b8a1.png)

**Comment by HariPriyaKuberSingh** [comment] 2022-10-19 11:45
@SalimF  - The fix is now live. Can you please confirm if the issue is fixed

**Comment by HariPriyaKuberSingh** [comment] 2022-11-03 10:52
@SalimF  - The fix is now live. Can you please confirm if the issue is fixed

**Comment by SalimF** [comment] 2022-11-05 02:00
> @SalimF - The fix is now live. Can you please confirm if the issue is fixed

Sorry, I didn't use _soft sub_ on my website anymore, but I'll try to test it soon.

**Comment by HariPriyaKuberSingh** [comment] 2022-11-14 12:30
@SalimF  - Thanks for the comment. Can you please let us know if you have validated the same in your website?

**Comment by HariPriyaKuberSingh** [comment] 2022-11-25 14:01
Tested the ticket from the QA side and it is working as expected. @SalimF: If the issue persists, feel free to open a new ticket with the details, and we will address it accordingly. Closing the ticket

**Closed by HariPriyaKuberSingh** 2022-11-25 14:01 UTC
Labels: question, needs triage
