### ISSUE TITLE
Option to disable basic android function long tap

### ISSUE THREAD

**Issue by devsdocs** [fluid-player/fluid-player#568] opened 2021-04-10 07:03 UTC
When using Fluid Player, user in mobile (Android) can easily direct download video by long tap on video, then a pop up showing user to download video directly. 

How can I disable this?

Thank you.

**Comment by leroybm** [comment] 2023-09-07 10:08
@devsdocs I've just checked and couldn't reproduce this. Since this issue is quite old, can you test again, or close the issue?

**Closed** 2023-09-10 14:27 UTC
Labels: question, needs triage
