### ISSUE TITLE
Support for Ad Pods

### ISSUE THREAD

**Issue by VitalyOrbit** [fluid-player/fluid-player#565] opened 2021-03-01 08:57 UTC
There is an VAST with ad pods, but player doesn't play first ad at least.

```xml
<VAST version="4.1">
<Ad sequence="0">...</Ad>
<Ad sequence="1">...</Ad>
<Ad sequence="2">...</Ad>
</VAST>
```

**Additional context**
This feature is described here: [VAST 3.0](https://iabtechlab.com/wp-content/uploads/2016/04/VASTv3_0.pdf) Chapter 2.2.2

**Comment by HariPriyaKuberSingh** [comment] 2023-01-12 12:49
@VitalyOrbit  - Can you provide more information on the issue please ?or confirm if the issue is still reproducible

**Comment by VitalyOrbit** [comment] 2023-01-12 13:16
> @VitalyOrbit - Can you provide more information on the issue please ?or confirm if the issue is still reproducible

For example, you can use this URL: https://cdnzone.nuevodevel.com/pub/5.0/e-a-1/vast_adpods_sample2.xml
I have just tested and seen only the first ad.

OK, let's step-by-step.
1. I opened the page https://www.fluidplayer.com/#demo.
2. Specified the VAST URL (I used preroll).
3. Copied the generated code to the page and run.

I saw only the first ad.

**Comment by HariPriyaKuberSingh** [comment] 2023-03-31 08:19
@VitalyOrbit  - The fix is in production. Can you please confirm if the issue is resolved

**Comment by VitalyOrbit** [comment] 2023-03-31 09:06
@HariPriyaKuberSingh, I'm getting these messages now:

Access to XMLHttpRequest at 'https://cdnzone.nuevodevel.com/pub/5.0/e-a-1/vast_adpods_sample2.xml' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

[Error] (101): Failed to load Vast

[Error] (900): Failed to load Vast

GET https://cdnzone.nuevodevel.com/pub/5.0/e-a-1/vast_adpods_sample2.xml net::ERR_FAILED 200

**Comment by leroybm** [comment] 2023-03-31 15:07
Hi @VitalyOrbit, It seems that the problem that you mentioned is just a common CORS problem, can you check the Ad Pod support with another host?

I've taken the liberty to upload the provided VAST to a test host and to create a simple test, you can check it here:
https://scrawny-rare-purple.glitch.me/

If you change the Fluid Player version you can see the difference between the same VAST with Ad Pods rendering in the latest version and on a previous version

**Comment by HariPriyaKuberSingh** [comment] 2023-04-14 10:46
@VitalyOrbit  - Can you please confirm if the suggestion by @leroybm helped you with the fix ?

**Comment by VitalyOrbit** [comment] 2023-04-14 11:07
@leroybm, @HariPriyaKuberSingh.
It works.

But can you also solve the CORS issue too? I use to use vast contents from different hosts.
Ad Serving systems send their VAST URLs.

**Comment by leroybm** [comment] 2023-04-17 10:01
@VitalyOrbit, the CORS issue is not related to Fluid Player, but on what website you are hosting Fluid Player and the VAST URLs. Normally Ad Servers don't have issue with CORS, since it's in their best interests that the Ads will be properly displayed. The problem in this stance specifically is that the URL you provided is just a sample and was not properly set up to be used in all cases.

**Comment by VitalyOrbit** [comment] 2023-04-17 10:31
Ok, then this issue can be closed.

**Comment by HariPriyaKuberSingh** [comment] 2023-04-17 10:57
@VitalyOrbit - Based on the above comment, closing the ticket

**Closed by HariPriyaKuberSingh** 2023-04-17 10:57 UTC
Labels: question, needs triage
