### ISSUE TITLE
Safari iOS Fluid Player - needs to click the play button twice to Play

### ISSUE THREAD

**Issue by PostMalone** [fluid-player/fluid-player#672] opened 2022-07-23 08:19 UTC
**Describe the bug**
When trying to watch the video through Fluid Player on Safari, in order to play it you must click on play button twice.
When you click on it first time controls bar show up. When you click on it the second time, the video plays.

**To Reproduce**
1. Go to '(https://www.fluidplayer.com/#demo)'
2. Click on Play button
3. Click again
4. Replicated

**Expected behavior**
I expected that when you click on play button once, the video plays. This works for any other Video Player.

**Screenshots or Links**
/

**Desktop (please complete the following information if relevant):**
/

**Smartphone (please complete the following information if relevant):**
 - Device: iPhone 11
 - OS: iOS 15.6
 - Browser: Safari
 - Version: 15.4

**Affected version**
v3.0.0

**Additional context**
/

**Comment by HariPriyaKuberSingh** [comment] 2022-10-12 15:50
@PostMalone  - Can you please confirm if the issue is still reproducible?

**Comment by HariPriyaKuberSingh** [comment] 2022-11-03 10:48
Closing the ticket since there is no update on the issue

**Closed by HariPriyaKuberSingh** 2022-11-03 10:48 UTC
Labels: bug, needs triage
