### ISSUE TITLE
async loading

### ISSUE THREAD

**Issue by biguz** [fluid-player/fluid-player#772] opened 2023-10-16 07:15 UTC
Can you please explain proper way to async or defer loading fluidplayer.min.js
now we use such script to detect fluidPlayer method

var fluidPlayerPlugin0 = function() {
var myFP = fluidPlayer(
playerId,
options
);
};
(function defer() {
if (typeof(fluidPlayer) != 'undefined') {
fluidPlayerPlugin0();
} else {
setTimeout(defer, 50);
}
})();

usually it works good, but sometimes on a slow 3g connection poster image loading twice: first time when preload and second after load event

**Comment by sergiomcsousa** [comment] 2024-02-28 11:54
@ZentoDH Can you please provide feedback here? If you think an internal ticket should be created please let me know. Thank you!

**Comment by ZentoDH** [comment] 2024-04-10 13:01
@biguz Sorry for the late response. 

I'm not able to reproduce your issue. I've used the slow 3g function in chrome dev tools. Could you reproduce it in codepen or something similar?

Thanks!

**Comment by sergiomcsousa** [comment] 2024-05-13 10:56
@biguz since there's no feedback on this issue I will close this ticket. If the problem still persists please let us know and open it again. Thank you!

**Closed by sergiomcsousa** 2024-05-13 10:56 UTC
Labels: question

**Comment by oscarhandsome** [comment] 2024-10-15 10:41
in pure js **_onload_**
in jquery **_.on('load', function(){})_**
after that you can use async or defer when you attach script in HTML
