### ISSUE TITLE
VAST + VPAID conflict bug

### ISSUE THREAD

**Issue by Barahten** [fluid-player/fluid-player#558] opened 2021-02-11 15:29 UTC
In the process of testing the advertising functions of the player version 3, the following problems were found with the simultaneous use of VAST and VPAID tags

### Example 1
For example the following configuration works correctly:
```
adList: [
  {roll: 'preRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=2366423'}, // Linear VAST, skippable
  {roll: 'midRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233', timer: 8},// Linear VAST, skippable
  {roll: 'postRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233'},// Linear VAST, skippable
]
```
### Example 2
The following configuration throws errors

```
adList: [
  {roll: 'preRoll', vastTag: 'vpaid_linear.xml'}, // Linear VPAID, skippable
  {roll: 'preRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=2366423'}, // Linear VAST, skippable
  {roll: 'midRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233', timer: 8},// Linear VAST, skippable
  {roll: 'postRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233'},// Linear VAST, skippable
]
```
Pre-rolls and Mid-rolls are played correctly, when the Post-roll starts playing, an error appears in the console
<img src="https://i.ibb.co/fdF7nzv/2021-02-11-180315.png" alt="2021-02-11-180315" border="0">
### Example 3

The following configuration throws errors

```
adList: [
  {roll: 'preRoll', vastTag: 'vpaid_linear.xml'}, // Linear VPAID, skippable
  {roll: 'preRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=2366423'}, // Linear VAST, skippable
  {roll: 'midRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233', timer: 8},// Linear VAST, skippable
  {roll: 'midRoll', vastTag: 'vpaid_linear.xml', adText: 'Advertising supports us directly'}, // Linear VPAID, skippable
  {roll: 'postRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233'},// Linear VAST, skippable
]
```
Both Pre-rolls are played correctly, VAST mid-roll is played correctly, VPAID Mid-roll automaticalky is skipped and not played, Post-roll is not played, an error appears in the console
<img src="https://i.ibb.co/fdF7nzv/2021-02-11-180315.png" alt="2021-02-11-180315" border="0">
### Example 4

Тhe following configuration works correctly:
```
adList: [
  {roll: 'preRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=2366423'}, // Linear VAST, skippable
  {roll: 'midRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233', timer: 8},// Linear VAST, skippable
  {roll: 'postRoll', vastTag: 'vpaid_linear.xml', adText: 'Advertising supports us directly'}, // Linear VPAID, skippable
  {roll: 'postRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233'},// Linear VAST, skippable
]
```
### Example 5

Тhe following configuration works correctly:
```
adList: [
  {roll: 'preRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=2366423'}, // Linear VAST, skippable
  {roll: 'preRoll', vastTag: 'vpaid_linear.xml', adText: 'Advertising supports us directly'}, // Linear VPAID, skippable
  {roll: 'midRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233', timer: 8},// Linear VAST, skippable
  {roll: 'postRoll', vastTag: 'vpaid_linear.xml', adText: 'Advertising supports us directly'}, // Linear VPAID, skippable
  {roll: 'postRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233'},// Linear VAST, skippable
]
```
In this configuration, all rolls are played correctly, only the VPAID Post-roll is automatically skipped and not played

### Example 6
Тhe following configuration works correctly:
```
adList: [
  {roll: 'preRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=2366423'}, // Linear VAST, skippable
  {roll: 'preRoll', vastTag: 'vpaid_linear.xml', adText: 'Advertising supports us directly'}, // Linear VPAID, skippable
  {roll: 'midRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233', timer: 8},// Linear VAST, skippable
  {roll: 'postRoll', vastTag: 'vpaid_linear.xml', adText: 'Advertising supports us directly'}, // Linear VPAID, skippable
  {roll: 'postRoll', vastTag: 'vpaid_linear.xml', adText: 'Advertising supports us directly'}, // Linear VPAID, skippable
  {roll: 'postRoll', vastTag: ' https://syndication.exosrv.com/splash.php?idzone=3165233'},// Linear VAST, skippable
]
```
In this configuration, all rolls are played correctly, only VPAID Mid-roll and VPAID Post-roll are automatically skipped and not played

**Comment by leroybm** [comment] 2022-08-23 10:30
Hi @Barahten, these errors are happening because vpaid_linear.xml is loading a test VPAID script that doesn't fully implement the VPAID 2.0 specs. More specifically it doesn't always clears up the callback methods required by VPAID. You can retry the tests with another VPAID XML that properly implements the VPAID 2.0 spec, and it should work.

I'll close the issue for now as it is not a bug with Fluid Player, but rather the VPAID XML used for testing.

**Closed by leroybm** 2022-08-23 10:30 UTC
Labels: bug, needs triage
