### ISSUE TITLE
Getting clickthroughurl in callbacks?

### ISSUE THREAD

**Issue by Luppakorva** [fluid-player/fluid-player#519] opened 2020-08-31 16:25 UTC
Version 3

I'd need to get the clickthroughUrl in vastLoadedCallback. I unfortunately can't get it from the html as it seems to be built in  feature. I need to pass it as url outside of the player. 

Is this possible?

**Comment by HariPriyaKuberSingh** [comment] 2021-12-01 12:55
@Luppakorva -  can you please confirm if the issue is still reproducible or does this require additional support ?

**Comment by Luppakorva** [comment] 2021-12-01 19:19
> @Luppakorva - can you please confirm if the issue is still reproducible or does this require additional support ?

I honestly can't right now. It's been quite a while since I was battling with the issue. You can close it but I can reapproach it if needed in near future (soon to be working with related code again)

Thanks for getting back to me eventually though!

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 11:17
Closing the ticket based on the above comment

**Closed by HariPriyaKuberSingh** 2021-12-24 11:17 UTC
Labels: question, needs triage
