### ISSUE TITLE
 image freezing

### ISSUE THREAD

**Issue by marceloaraujo28** [fluid-player/fluid-player#770] opened 2023-10-10 03:36 UTC
There is a moment in the video, while loading, the image freezes, but the sound and timeline continue to progress. This happens most often when I try to fast forward the video.

Please note that this issue doesn't occur on the web, only on mobile. Is there a way to perhaps, when fast forwarding the video, wait for it to buffer for a certain period before it can play, similar to how it behaves at the beginning? Or is there a better solution available?

I already tried this:
"modules": {
"configureHls": (options) => ({
"maxMaxBufferLength": 30,
"startLevel": 4,
"autoStartLoad": true,
...options,
}),
},

**Comment by Fathomed** [comment] 2023-10-31 04:05
I am having the same problem.

**Comment by mcorbelli** [comment] 2024-01-24 09:45
Any update?

**Comment by sergiomcsousa** [comment] 2024-02-28 11:53
An internal ticket was created to take care of this issue. Thank you!

**Comment by ZentoDH** [comment] 2024-08-01 12:21
Hi @marceloaraujo28,

To provide some context, I tested this on a standard `<video>` tag and noticed the issue still occurred. This is likely because Chrome on Android, for example, supports HLS natively, but the implementation isn't great. In Fluid Player, we check for native HLS support, and if it's present, we skip loading HLS.js, instead relying on the browser's native HLS handling.

We found that HLS.js works a bit more consistently, not perfect, but better. The problem with native HLS is that the browser has all the control over stuff like `maxMaxBufferLength`, you can't change it. With HLS.js you have a lot more control over stuff like that. The more I work with HLS, I notice support is quite bad over the board. 

I've added a flag that allows you to override native HLS support when available, and instead force the use of HLS.js. This way you have more control.

```html
<script>
fluidPlayer(
    'hls-video',
    {
        hls: {
            overrideNative: true
        }
    }
);
</script>
```

**NOTE**: if you're using the `https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js`, it takes 24h for the cache to update so the change might not be there if you test it today. You'll have to use `https://cdn.fluidplayer.com/3.35.0/fluidplayer.min.js` if you want to use it today.

**Comment by marceloaraujo28** [comment] 2024-08-08 02:24
@ZentoDH @sergiomcsousa Thank you for your attention!

**Comment by Kasamsun151a** [comment] 2024-08-08 19:26
> @ZentoDH @sergiomcsousaขอขอบคุณสำหรับความสนใจของคุณ!
https://github.com/fluid-player/fluid-player/issues/770#issuecomment-2274821842

**Comment by brunopick** [comment] 2024-08-09 09:27
@marceloaraujo28 Sorry, it wasn't clear if the issue was fixed for you. Could you further explain? Thanks.

**Comment by sergiomcsousa** [comment] 2024-08-19 17:29
@ marceloarau28 Can you please provide feedback as this comment says? https://github.com/fluid-player/fluid-player/issues/770#issuecomment-2277537136 and if the issue is fixed can you please close it? Thank you!

**Closed** 2024-08-19 17:30 UTC
Labels: bug
