### ISSUE TITLE
Any plans to support Google Ad Manager/ IMA SDK?

### ISSUE THREAD

**Issue by rgreen3400** [fluid-player/fluid-player#476] opened 2020-06-19 14:17 UTC
Hi,
We love Fluidplayer but would like to use with Google ADX/ Google Ad Manager. Any plans to support this?
https://support.google.com/admanager/answer/186110?hl=en

Thanks...

**Comment by jianfai** [comment] 2020-07-21 11:23
Just want to second that feature request.

**Comment by HariPriyaKuberSingh** [comment] 2021-11-30 12:59
@rgreen3400  @jianfai  - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment] 2021-12-16 17:03
@rgreen3400 @jianfai - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 11:02
Closing this issue since there is no confirmation regarding the issue being reproducible

**Closed by HariPriyaKuberSingh** 2021-12-24 11:02 UTC
Labels: feature request, needs triage

**Comment by FarisYaseen** [comment] 2022-08-06 13:05
hello is this issue has been resolved ? is there a plug in can we use it ?
