### ISSUE TITLE
Mouse disappers after leaving Player

### ISSUE THREAD

**Issue by JKusber** [fluid-player/fluid-player#317] opened 2019-03-03 18:30 UTC
If you leave the player with the mouse (for example, if you go over the bookmarks bar), it no longer appears on the player. This makes it very difficult to click the play button because you can't see the mouse over the player. I can do this with the Chrome Browser on the demo page of the fluidplayer (I haven't tested it with other browsers until now).

I think thats a general bug of the player, or? Is there a quick fix for that?

**Comment by JKusber** [comment] 2019-03-03 18:35
I tested it again: It's the same in edge for example!

**Comment by Addvilz** [comment] 2020-02-10 14:56
Can you explain a little more, step by step? Not able to reproduce the issue.

**Comment by JKusber** [comment] 2020-02-10 15:12
Sorry I don't use the player anymore so I can't check it anymore. The problem was that the mouse disappeared when you moved down from the video player and was behind the video player when you moved back over it.

**Comment by Addvilz** [comment] 2020-02-10 15:16
@JKusber do you by any chance have more than 1 monitor connected? I have noticed similar behavior on webkit based browsers before on multi-monitor systems, involving other HTML5 players. I think it has something to do with how WebKit renders the HTML5 video element in this particular case.

If not, either way - can't seem to be able to reproduce.

**Comment by JKusber** [comment] 2020-02-10 16:55
Yes I had 2 monitores... Maybe thats the reason. I can't repoduce it on the fluid player site, now. Maybe it's fixed... The topic is already one year old.

**Comment by Addvilz** [comment] 2020-02-10 16:58
All right, thank you for your input! Closing for now as not reproducible.

**Closed by Addvilz** 2020-02-10 16:58 UTC
Labels: need more info
