### ISSUE TITLE
New event suggestion, onError

### ISSUE THREAD

**Issue by F4brizio** [fluid-player/fluid-player#545] opened 2020-11-30 09:45 UTC
### New Event API

**onError**: Fired when an error occurs after initialization or reproduction video.

- Invalid mp4 url (Broken Link)
- Invalid format

Something like this:
`player.on('onError', function(){ console.log('The video could not be played!'); });`

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 11:22
@F4brizio - can you please confirm if the issue is still reproducible ?

**Comment by F4brizio** [comment] 2021-12-26 05:05
Yes please.

**Comment by marcofbb** [comment] 2023-01-14 19:16
I need it :(

**Comment by DaRealCoda3** [comment] 2023-01-14 19:21
Bro I got more than that ... 

BloxkOnlyVibez ... I'm bro let's connect

**Comment by leroybm** [comment] 2023-09-08 09:11
Duplicated of #241, we have an internal ticket to take care of this. Closing.

**Closed by leroybm** 2023-09-08 09:11 UTC
Labels: feature request, needs triage
