### ISSUE TITLE
Does not use passive listeners to improve scrolling performance

### ISSUE THREAD

**Issue by kmexdelad** [fluid-player/fluid-player#759] opened 2023-08-20 12:13 UTC
When I do the test on google pagespeed this message appears:
**Does not use passive listeners to improve scrolling performance**

Using the player on the cell phone it is possible to visualize the problem, when I try to scroll the page by clicking on the player it triggers the video instead of scrolling naturally.

This affects the user's navigation on the page, please fix this problem.

In pagespeed they indicate this page:
https://developer.chrome.com/docs/lighthouse/best-practices/uses-passive-event-listeners/

Thanks

**Comment by leroybm** [comment] 2023-08-22 10:45
Hi @kmexdelad, this is a duplicate of #404. There's already a PR for this, expect it to be fixed in the coming weeks. I'll close this for now.

**Closed by leroybm** 2023-08-22 10:45 UTC
Labels: bug, needs triage
