### ISSUE TITLE
Playback start broken on v3

### ISSUE THREAD

**Issue by majamee** [fluid-player/fluid-player#452] opened 2020-05-22 23:12 UTC
Hi,
I found the following issue.

Background: 
Version 2 and Version 3 of fluid player use exactly the same source files for video playback.

Expected behavior:
Clicking on play starts video playback. This is true for v2, but not for v3.

Actual behavior:
v3 doesn't start the playback at all, instead the following issues are reported in the web console:
`[SourceBufferSink] SourceBuffer append failed "InvalidStateError: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source."`

Can be tested here:
- Working v2: https://majamee.000webhostapp.com/player/fluid-player.html
- Not-working v3: https://majamee.000webhostapp.com/player/fluid-player-v3.html

I would appreciate, if you could have a look at it, especially as the video files are untouched and shared between the two versions.

Thanks & BR, majamee

**Comment by Addvilz** [comment] 2020-05-23 09:39
This looks like coming from dash.js - we did bump a couple of minor versions with V3 - from 3.0.0 to 3.0.3.

**Comment by Addvilz** [comment] 2020-05-28 10:49
Reproduced and affects both v2 and v3, with some differences. The issue is intermittent - sometimes happens, sometimes does not. I suspect due to buffer states of the stream. It also behaves differently depending on whether it's VOD or live stream.

This definitely has something to do with dashjs.

**Comment by Addvilz** [comment] 2020-05-28 12:18
Gets better - it does not seem the above error is actually related. Sometimes playback continues just fine with the error there and sometimes it does not. What is more interesting is that dash.js triggers `playbackPlaying` event regardless if the there is actual video playing or not.

**Comment by Addvilz** [comment] 2020-05-28 13:53
The issue has been identified - dash.js comes with a "feature" called autoCreate - it would attach to all video sources automatically once loaded to a page. Incidentally, Fluid Player always attaches it's own instances of dash.js to the sources when necessary. This double loading of dash causes race conditions and thus the player breaks. 

Fix will be released with v3.0.1.

**Comment by majamee** [comment] 2020-05-28 18:27
Awesome, thanks for checking. Looking forward to your next release :)

**Closed** 2020-05-29 10:13 UTC
Labels: bug, vendor

**Comment by Addvilz** [comment] 2020-05-29 10:29
This should now be fixed with the latest release.
