### ISSUE TITLE
How to include fluid-icons.svg into fluidplayer.js?

### ISSUE THREAD

**Issue by gibigate** [fluid-player/fluid-player#779] opened 2023-11-15 12:38 UTC
i trying compile new version 3.27.0, everything ok except fluid-icons.svg, these icons loaded from cdn.fluidplayer.com, how to change this behaviour? How to include these icons into compiled fluidplayer.min.js?

**Comment by sergiomcsousa** [comment] 2024-02-28 12:06
@ZentoDH can you please provide some feedback here? Do you think that it is necessary to create an internal ticket? Thank you!

**Comment by ZentoDH** [comment] 2024-04-10 10:48
@gibigate Hi there, sorry for the massive delay.
I'm not able to reproduce what you're saying or I'm not fully understanding what you mean. Could you maybe reproduce it in codepen or something like that? 

Thanks!

**Comment by sergiomcsousa** [comment] 2024-05-13 10:57
@gibigate @biguz since there's no feedback on this issue I will close this ticket. If the problem still persists please let us know and open it again. Thank you!

**Closed by sergiomcsousa** 2024-05-13 10:57 UTC
Labels: question
