### ISSUE TITLE
When adblock enabled with VAST, video is transparent but audio stars playing

### ISSUE THREAD

**Issue by namethatporn** [fluid-player/fluid-player#339] opened 2019-05-01 15:07 UTC
**Setup:** Latest Chrome (74.0.3729.131) on Mac Mojave

**Problem:** Video page loads up, with correct thumbnail. When pressed play, the audio starts but video itself is transparent. Console shows, that the VAST file is blocked off by client (adblock).

**Where:** You can see the reproduction of the problem here (lol..didn't expect this one, didn't you..):
https://www.fluidplayer.com/video-advertising/

![Screenshot 2019-05-01 at 18 03 41](https://user-images.githubusercontent.com/32296911/57023840-c70e8a80-6c3b-11e9-80c0-2ca5d82542ea.png)

My only idea right now is to detect if there is adblock and then not show ads at all. But if anything, those people should get more ads. So overall this is a project halting problem.

**Comment by Addvilz** [comment] 2020-06-16 09:37
Can reproduce, but this seems to have something to do with AdBlock itself plus the page, not just the page.

All ad features are tested with uBlock Origin and AdBlock - and it works just fine both in e2e test cases and in docs for example. But it does do something weird in that particular page specifically though.

I think what is happening here is that AdBlock is just removing or modifying some player element based on it's class name or other attributes on that page. This needs to be investigated further.

**Comment by HariPriyaKuberSingh** [comment] 2021-11-10 16:10
@namethatporn  are you still facing this issue?

**Comment by HariPriyaKuberSingh** [comment] 2021-11-30 12:39
@namethatporn - Can you please confirm if the issue resolved or does it still exist ?

**Comment by HariPriyaKuberSingh** [comment] 2021-12-16 15:21
Closing the ticket since there is no confirmation from the reporter

**Closed by HariPriyaKuberSingh** 2021-12-16 15:21 UTC
Labels: bug
