### ISSUE TITLE
Playback controls not available on iOS in iFrame

### ISSUE THREAD

**Issue by majamee** [fluid-player/fluid-player#172] opened 2018-05-23 18:10 UTC
Dear Fluid Player Devs,
I just tested your latest release of Fluid Player with the native fullscreen fix on iOS and noticed, that I can invoke play, but then no more player controls appear. The only way to interact with the player from this point on is to use the zoom gesture on the video player to invoke native fullscreen and use then the native playback controls.
Can you please check?
You can test at: http://alpine-dash-hls.gq/demos/fluid-player

(Might be connected to iframe or DASH/ HLS maybe)

**Comment by cian-exads** [comment] 2018-05-24 09:45
I've been able to reproduce this @majamee, however it doesn't seem to happen every time for me and sometimes works fine. There's something happening anyway, so will take a look into it! Thank you for the feedback as always, much appreciated!

**Comment by majamee** [comment] 2018-05-24 10:53
Hi @cian-exads, yes I can confirm that the bug is not 100% persistent, also my testing showed that. For some reason it was more successful to invoke the correct behavior when opening the player first as background tab and then switch. Don't know why though. Another time it was looking fine until the player area was entered (by touch).

**Comment by HariPriyaKuberSingh** [comment] 2021-11-10 11:18
@majamee - Does the issue still persist?

**Comment by HariPriyaKuberSingh** [comment] 2021-11-30 12:26
@majamee  - can you please confirm if the issues persist ?

**Comment by HariPriyaKuberSingh** [comment] 2021-12-16 14:59
Closing this ticket since there is no confirmation from the reporter

**Closed by HariPriyaKuberSingh** 2021-12-16 14:59 UTC
Labels: bug
