### ISSUE TITLE
Vast + browser layout causes issues

### ISSUE THREAD

**Issue by tapplz** [fluid-player/fluid-player#118] opened 2018-04-08 17:07 UTC
When using layout 'browser' the preroll video will play but at the end of the video it'll freeze and not play the main video. If I choose not to have a preroll and send an empty <VAST></VAST> to it, it freezes without playing anything.

Using default layout works fine, but second issue:
When using default layout and fill to container, when going fullscreen the video doesn't fill the screen, as if it's still under the previous containers size limitation. I've noticed this on Desktop chrome and firefox, not on mobile (android). 

Using 2.1.2

Side note, you're doing great with this player. Love seeing all the active development and fast responses to issues.

What the browser is showing me:

Using layout 'browser':
Firefox 59.0.2
TypeError: Argument 1 of Window.getComputedStyle is not an object. fluidplayer.min.js:1:57959
TypeError: t is null	fluidplayer.min.js:1:59615
TypeError: Argument 1 of Window.getComputedStyle is not an object. fluidplayer.min.js:1:57959

Chrome 65.0.3325.181
[Error] (401): Failed to load Vast
Uncaught TypeError: Cannot read property 'style' of null
	at Object.setBuffering (fluidplayer.min.js:1)    
	at Object.switchToMainVideo (fluidplayer.min.js:1)    
	at Object.playMainVideoWhenVastFails (fluidplayer.min.js:1)    
	at HTMLVideoElement.onErrorDetection (fluidplayer.min.js:1)
setBuffering @ fluidplayer.min.js:1
switchToMainVideo @ fluidplayer.min.js:1
playMainVideoWhenVastFails @ fluidplayer.min.js:1
onErrorDetection @ fluidplayer.min.js:1
error (async) init @ fluidplayer.min.js:1
fluidPlayer @ fluidplayer.min.js:1
success @ test.js:43
i @ jquery-2.2.0.min.js:2
fireWith @ jquery-2.2.0.min.js:2
z @ jquery-2.2.0.min.js:4
(anonymous) @ jquery-2.2.0.min.js:4
load (async) send @ jquery-2.2.0.min.js:4
ajax @ jquery-2.2.0.min.js:4
(anonymous) @ test.js:36
setTimeout (async)
loadVideo @ test.js:16
(anonymous) @ test.js:3973
fluidplayer.min.js:1 

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.    
	at Object.isControlBarVisible (fluidplayer.min.js:1)   
	at fluidplayer.min.js:1
	isControlBarVisible @ fluidplayer.min.js:1
	(anonymous) @ fluidplayer.min.js:1
	setTimeout (async) handleMouseleave @ fluidplayer.min.js:1

**Comment by cian-exads** [comment] 2018-04-10 08:44
Hi @tapplz, thanks for the feedback, an active community helps us identify the areas that need improvement so we appreciate messages like these.

First issue, I've reproduced this myself and will put a fix in place.
Regarding your second issue I haven't seen this behaviour before. Is the player in an iframe perhaps? If you could paste a copy of the code here or perhaps link to a demo page where I can see this occur that would be great.

**Comment by tapplz** [comment] 2018-04-11 16:46
[This is a test link](https://www.jillinoff.com/watch.php?vid=15095&fluidplayer2test=true) (Adult Content)

It uses the normal HTML 5 Video tag, and this config set up:

var testVideo = fluidPlayer('vidplayer',  {
layoutControls: {
	fillToContainer: true,
	primaryColor: "#af0c60",
	autoPlay: false,
	playButtonShowing: true,
	playPauseAnimation: true,
	mute: false,
	layout: 'default',
	logo: {
		imageUrl: '<img url>',
		position: 'top left',
		clickUrl: '<url to video>',
		opacity: 0.8
	},
	htmlOnPauseBlock: {
		html: null,
		height: null,
		width: null
	},
	allowDownload: false,
	allowTheatre: false,
	playbackRateEnabled: false,
	controlBar: {
		autoHide: true,
		autoHideTimeout: 1,
		animated: true
	},
},
vastOptions: {
	adList:                     [{
		roll: 'preRoll',
		vastTag: '<Vast xml url>'
	}],
	skipButtonCaption:          '[seconds]',
	skipButtonClickCaption:     'Skip',
	adText:                      null,
	vastTimeout:                 5000,
}
});

**Comment by tapplz** [comment] 2018-04-11 16:51
It's wrapped in a div that adjusts in size based on the window width, so the video will shrink/grow based on your view port size. Seems the constant isn't being ignored when transitioning to full screen.

**Comment by cian-exads** [comment] 2018-04-12 08:30
Hi @tapplz, this is occurring due to a **max-height: 600px;** on the **#vidplayer** element. This is around line **421** of **black.css**. This restriction is on the video itself and not the wrappers, causing the fullscreen to occur but the video to remain within it's restrictions. In my tests locally removing this line causes the video and page to work correctly. Can you try removing this line and confirming if the behaviour is as expected?

I will bring up this issue with the developer to discuss possible fixes for similar cases in the future.

**Comment by tapplz** [comment] 2018-04-13 14:13
That works for normal 16:9 wide videos, but without the max height portrait videos do 100% width and scroll down the page. The Filltocontainer option doesn't detect and decide which is more appropriate (width:100% vs height:100%) so the max-height css corrects for that.

**Comment by ShpendBerisha** [comment] 2018-06-03 07:10
When we use banner in video it doesn't work for me too but with instream video its working fine without problems.

**Comment by cian-exads** [comment] 2018-06-12 08:45
@ShpendBerisha can you link me to a test page where I can see the issues occur?

**Comment by ShpendBerisha** [comment] 2018-06-14 07:47
Hello the problem is that its an adult content I don't know where to post it.

**Comment by cian-exads** [comment] 2018-06-18 08:23
@ShpendBerisha if you don't wish to post the link here you can email it to me directly at **cian@exads.com**

**Comment by tudy000** [comment] 2018-06-25 21:10
Same thing happens on this site,with the full screen i mean,in chrome PC and waterfox PC i don;t mind t's adult content link,here it is https://www.heavy-r.com/video/319522/Cum_Load_On_Face/

**Comment by cian-exads** [comment] 2018-06-26 08:19
@tudy000 this is due to **#video-file { max-height: 520px; }** forcing a pixel restriction on the video itself, not the player.

**Comment by tudy000** [comment] 2018-06-26 23:48
But cian-exads,all the clips have the same problem,none of them go properly fullscreen,so what's the deal with that?

**Comment by cian-exads** [comment] 2018-06-27 08:30
@tudy000 the css applies to the video element on the page, not just that particular clip. The fluid Player wrapper will resize freely as there is no custom css restricting it, normally applying resizes to the video as well. That's why the player is resizing but the video isn't.

**Comment by ShpendBerisha** [comment] 2018-06-27 09:17
Hi @cian-exads,  sorry for late response during this week I will send you in email some examples.
for @tudy000 I can recommend this piece of css code:
```
.fluid_video_wrapper {
    width: 100%;
    max-width: 100%;
    height: 0;
}
.fluid_video_wrapper {
    padding-top: 56.25%;
}
```

**Comment by Addvilz** [comment] 2020-02-27 11:57
Closing this issue as I can't seem to be able to reproduce given the information here at this time.

Feel free to reopen the issue if it still affects you.

**Closed by Addvilz** 2020-02-27 11:57 UTC
Labels: bug, needs triage
