### ISSUE TITLE
Fluid Player does not switch sources after playing m3u8

### ISSUE THREAD

**Issue by FriskIsGit** [fluid-player/fluid-player#841] opened 2024-10-06 12:47 UTC
**Describe the bug**
The player does not switch to any other media type (mp4/mkv) once HLS (m3u8) has played. The m3u8 keeps playing.
The quality switcher marks another media type as selected but it takes no action.

**Steps to Reproduce**
1. Use the webpage below
2. Click on video quality switcher
3. Click on mkv
4. Click on mp4
5. Click on hls
6. Click on either mkv or mp4 (the source won't actually change)

**Expected behavior**
Being able to switch freely between all media types and for the player to switch the source
Providing 

**Screenshots**
![m3u8-still-playing](https://github.com/user-attachments/assets/b0280496-6b43-4fde-b696-81c10d707b47)

**Platform**
 - OS: [ANY]
 - Browser [ANY]
 - Version [ANY]
 
```html
 <!doctype html>
<html lang="en-US">

<head>
    <meta charset="utf-8"/>
    <meta name="referrer" content="no-referrer">
    <title>Source switching</title>
</head>

<body>

<video id='my-player' controls style="width: 640px; height: 360px;">
    <source src='https://download.samplelib.com/mp4/sample-10s.mp4' title='mp4' type='video/mp4'/>
    <source src='https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
            title='m3u8' type='application/x-mpegURL'/>
    <source src="https://cdn.fluidplayer.com/videos/valerian-1080p.mkv" type="video/mp4" title="mkv">
</video>

<!-- Place before </body> tag -->
<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
<script>
    var player = fluidPlayer('my-player', {
        hls: {
            overrideNative: true
        }
    });
</script>

<script src="https://cdn.fluidplayer.com/v3/current/fluidplayer.min.js"></script>
</body>

</html>

```

**Additional information**
Setting overrideNative to true or false has no effect. The issue still persists. It's a major oversight. Additionally there's no public API available for source switching, your best hope is to destroy the existing player and create it anew

**Comment by sergiomcsousa** [comment] 2024-10-17 11:31
An internal ticket was created to address this issue. Thank you!

**Comment by Ankit-Exads** [comment] 2024-10-25 10:18
After investigating the code behaves as intended. The video quality icon is present for the hls codec to set the desired video quality. Whereas in the ticket its being used to change the video codec i.e from mp4 to mk4 etc. Since m3u8 format already uses the same button to set the video quality we face the issue which is mentioned. The shown button button sets video quality and not set different codec we believe this is the correct behaviour. Hence no further action is needed on this.  So we will be closing this ticket.

**Closed by Ankit-Exads** 2024-10-25 10:18 UTC
Labels: bug

**Comment by FriskIsGit** [comment] 2024-10-26 19:18
Closed as "completed" when nothing has been **completed**. At least close it as "Won't Fix" and explain clearly in the documentation that your quality switcher is unable to switch between different codecs and you intend to keep that behavior.

**Comment by Mioshek** [comment] 2024-10-28 18:35
You guys have awesome "FEATURES"
