### ISSUE TITLE
Player required 2 clicks to play video New Iphone 11 Pro Chrome

### ISSUE THREAD

**Issue by Daisum** [fluid-player/fluid-player#511] opened 2020-08-21 10:58 UTC
**Describe the bug**
The video player required 2 clicks to play the video on Iphone 11 Chrome Mobile.
1st click shows the player control bar but does not play the video.
2nd click plays the video

**To Reproduce**
open chrome on mobile - Iphone 11 Pro Max
Click on video player to see the 2 click issue

**Expected behavior**
Player should play the video with 1 click and not require 2 clicks.

**Screenshots or Links**
Links are NSFW so can supply on demand.

**Smartphone (please complete the following information if relevant):**
 - Device: Iphone 11 pro max
 - OS:  iOS 13.6,
 - Browser Chrome version: 84.0.4147.122

**Affected version**
fluidplayer version v3.0.4

**Comment by jonbid** [comment] 2020-09-12 18:19
hello, we are experiencing the same issue. does anyone have a fix for this? it is very annoying and we are considering changing video players because of this!

**Comment by sanchezzzhak** [comment] 2020-09-27 09:30
playback should only be called when the video element is visible to the user + with the maximum response from the event.

1 download VAST the video before the user clicks the play video
2 when you click Play, create a video and place a video ad. ( this will allow you to perform a custom user action)

this scenario works for ios 12-14.

**Comment by jonbid** [comment] 2020-12-22 20:35
anyone find a solution to this problem yet?

**Comment by Daisum** [comment] 2020-12-23 11:50
no solution yet, very slow support unfortunately.

**Comment by Addvilz** [comment] 2020-12-24 11:08
@Daisum you are, as always, welcome to contribute a fix - this is an open source project.

**Comment by Daisum** [comment] 2020-12-24 11:24
@Addvilz unfortunately, like 99% of people using this player, I am not a developer able to contribute. The comment was not personal, just a fact that support is slow here.

**Comment by jonbid** [comment] 2021-01-20 00:45
this is a very annoying problem. seriously, does anyone even care about fixing this? it affects EVERY BROWSER.

**Comment by Addvilz** [comment] 2021-01-20 11:59
@jonbid we do care about fixing this - and every other issue there is with the player, however, resources available to us to address this issue at this time are limited. 

As always, this is an open source project - you, and everyone else is welcome to contribute a fix, if the issue is of high importance to you.

**Comment by jonbid** [comment] 2021-01-20 20:35
i would help if i knew how to program. it takes 2 taps to start video playback in this video player, and it's a bug that affects the player in every mobile browser -- this bug should be priority as it's causing people not to watch videos using the player, which means the user leaves the site. which means this video player will be used by a lot less websites. this bug should be a priority to fix.

**Comment by jonbid** [comment] 2021-01-22 19:06
if anyone can fix this issue i am willing to pay a bounty as well.

**Comment by sfdjo435** [comment] 2021-02-21 19:49
Is this still happening?

**Comment by jonbid** [comment] 2021-02-22 19:09
hi, yes it is, did you update the code to fix this issue? if so i can get it tested.

**Comment by jonbid** [comment] 2021-04-08 05:11
is anyone interested in fixing this bug? i will pay a bounty!

**Comment by sfdjo435** [comment] 2021-04-09 18:19
> is anyone interested in fixing this bug? i will pay a bounty!

@jonbid I would fix it, but I don't have any iOS device to reproduce it on. Does it happen on macOS too?

Also need an example site please.

E-mail me: stackerror@outlook.com

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 11:15
@Daisum  - can you confirm if the issue is still persisting ?

**Comment by OrlaKinsella** [comment] 2022-10-17 11:09
@Daisum - is this issue still occurring?

**Comment by sfdjo435** [comment] 2022-10-17 17:56
I can confirm this issue is still occurring as described.

**Comment by HariPriyaKuberSingh** [comment] 2022-10-20 15:31
@sfdjo435  - Thank you for confirming. We will ask our dev team to look into this

**Closed** 2023-06-07 15:38 UTC
Labels: bug, needs triage
