### ISSUE TITLE
Start time resets to 0

### ISSUE THREAD

**Issue by sfdjo435** [fluid-player/fluid-player#563] opened 2021-02-21 20:05 UTC
**Describe the bug**
When using the source mp4 URL with `#t=213` as: `https://myvideosite/videos/video.mp4#t=213`

![screenshot](https://i.imgur.com/iA0eyI1.png)

It will show up when loading the page, but will actually start at 0s when playing.

**To Reproduce**
1. Append `#t=100` after video URL source
2. Autoplay the video

**Expected behavior**
Expect to continue from the current time, instead of resetting to 0.

**Comment by leroybm** [comment] 2022-05-17 14:10
@sfdjo435 Tested this issue but could not reproduce it, adding `#t=100` seems to work correctly. Is the issue still happening? Are you able to provide a Codepen reproducing the issue?

**Comment by HariPriyaKuberSingh** [comment] 2022-06-15 10:47
@sfdjo435 - can you please confirm if the issue is still happening ?

**Comment by HariPriyaKuberSingh** [comment] 2022-08-25 11:58
closing the ticket since there is no update on the bug from the reporter

**Closed by HariPriyaKuberSingh** 2022-08-25 11:58 UTC
Labels: bug, needs triage
