### ISSUE TITLE
equirectangular video does not play properly 

### ISSUE THREAD

**Issue by sabuhish** [fluid-player/fluid-player#492] opened 2020-07-09 18:31 UTC
**Describe the bug**
I am using the library for rendering 360 equirectangular videos, unfortunately, I faced some issues, would like to receive a hint from the community.  2 different issues so far I realized.
at first,  when 360 equirectangular video rendered it starts on muted mode. it keeps replaying after it finishes.  Secondly not able to move in the video, only possible with cursors on the left-up side.

**Expected behavior**
I am expecting to get output like the one in the link.
https://fluidplayer-exads.firebaseapp.com/html/vr.html 

![Screenshot from 2020-07-09 22-34-09](https://user-images.githubusercontent.com/46589585/87077602-6e218580-c234-11ea-8114-78e1fe56a947.png)
![Screenshot from 2020-07-09 22-35-33](https://user-images.githubusercontent.com/46589585/87077673-8a252700-c234-11ea-94b3-8199388fa898.png)

**Screenshots or Links**
If applicable, add screenshots or links to help explain your problem. **DO NOT** include links to NSFW webpages. Preferably create code to reproduce using https://jsfiddle.net

**Desktop (please complete the following information if relevant):**
 - OS: Linux Debian Buster
 - Browser Chrome

**Affected version**
I am using version 3.0.0

![Screenshot from 2020-07-09 22-36-50](https://user-images.githubusercontent.com/46589585/87077787-b6d93e80-c234-11ea-898b-528679568a32.png)

**Comment by Addvilz** [comment] 2020-07-09 19:46
So couple of things here, in order

1. You are hard linking to v3.0.0 - it's a buggy version and you should use the latest current - `http://cdn.fluidplayer.com/v3/current/fluidplayer.min.js`. Unless you are absolutely sure you need a specific version, you should never link against it.
2. You do not need to manually link three.js or panolens - Fluid Player will not use the ones you linked unless loaded before Fluid Player. All the dependencies are dealt with automatically and manual overrides are not recommended for compatibility.
3. *It keeps replaying after it finishes* - this issue was fixed with 3.0.2 and does not happen in current.
4. `not able to move in the video, only possible with cursors on the left-up side` - how exactly you expecting to move? Please provide more details here. Unless you tell me what you are doing I can not reproduce it.
5. `it starts on muted mode.` - I was able to reproduce this, seems to be caused by panolens however. I will look into this. As a temporary workaround, you can use the code bellow. It is important to add the event listener before initializing Fluid Player, it will not work reliably otherwise. This should unmute the video on when player is ready to play. Consider that this will override mute settings from user on page reload, so you should remove this code once an update has been released (I will notify you in this issue).

```
    var video = document.getElementById('fluid-player-e2e-case');
    video.addEventListener('canplay', function () {
        video.muted = false;
    });
    var instance = fluidPlayer('fluid-player-e2e-case', {
        layoutControls: {
            showCardBoardView: true,
            showCardBoardJoystick: true
        },
    });
```

**Comment by marlin-dev** [comment] 2020-07-09 21:38
> 3\. 3.0.2

Thank you so much sir for your detailed information and your help! I highly appreciate, taking your time helping me out. I am amazed actually :)

1) I changed version to v3/current it works perfectly, issue gone.

2) I was doing some workaround with panolens.js, forgot to remove them. 

3) Yes, exactly it does not happen in the current v3 version.

4) Could you please check this link below, if you play the video you will be able to change your directions, easily move up, down left right or 360 turn around the while video is playing. Once you click you can easily drag-cursor 360. 

https://fluidplayer-exads.firebaseapp.com/html/vr.html 

But, using the library, it operates differently, what it does stops the video or replays. You cant even drag-cursor unfortunately.

5)Umm, well apparently  panolens.js,  was not causing this. I removed  panolens.js  library from my template still video mode was muted. The code snippet covers the issue right now, it is cool! Thank you for minding for features.

If you can help me out with the fourth statement, it would be grateful. Thanks again!!

**Comment by Addvilz** [comment] 2020-07-10 08:48
4. I am sorry I still do not follow what you mean with the navigation part. I can drag the video with the cursor just fine on Chrome and FF. Can you elaborate what exactly does not work for you for the navigation part?
5. What I meant is this is due to Fluid Player and Panolens integration, there is nothing you can do about it. It's a bug and will need to be investigated.

**Comment by marlin-dev** [comment] 2020-07-10 12:39
I have recorded a video about the current issue:

https://streamable.com/efwr3k

If you realized I am able to drag with the mouse in the first 20 seconds, after my custom implementation with the library it is only possible with cursors not with mouse. I hope this clarifies my issue

The link where I was able to move with mouse:

https://fluidplayer-exads.firebaseapp.com/html/vr.html

**Comment by HariPriyaKuberSingh** [comment] 2021-11-30 13:15
@sabuhish - can you please confirm if the issues is persisting or resolved

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 11:03
Closing this issue since there is no confirmation regarding the issue being reproducible

**Closed by HariPriyaKuberSingh** 2021-12-24 11:03 UTC
Labels: bug, need more info, needs triage
