### ISSUE TITLE
Looping videos show loading spinner for a split second before looping

### ISSUE THREAD

**Issue by sinni800** [fluid-player/fluid-player#205] opened 2018-06-03 23:17 UTC
I wonder if this can be prevented. If you use the browser layout, it will still pause for a split second (more than the browser does natively without fluidplayer at all) but not show a spinner. 

Edit: After investigating more, the split second pause seems to stem from the fact that the css for the darkening screen is fading in. So basically, if the video is looping, don't let the class for the loading spinner take effect. 

I worked around this problem by throwing out the loading spinner entirely... Which is a sacrifice, but not as bad as the almost epilepsy inducing screen darkening and annoying loading spinner coming up. This is especially "egregious" if the video is less than a second long, which occurs with our (user-submitted) content.

```
.fluid_video_wrapper .vast_video_loading:before {
    /*background-image: url("images/fluid_spinner.svg");*/
    background-position: center center;
    background-repeat: no-repeat, repeat;
    /*background-color: rgba(0, 0, 0, 0.2);*/
    content: '';
    position: absolute;
    height: 100%;
    width: 100%;
    top: 0;
    left: 0;
}
```

**Comment by cian-exads** [comment] 2018-06-05 08:16
Hi @sinni800, I'll bring this up to be discussed further, but the spinner is trigger by the video events. If it's showing it's because the video has triggered it, which is correct but unwanted for such short videos. Perhaps the solution may be to give the option to turn it off in the Fluid Player parameters, rather than manually doing it. As said, I will look to get this discussed further.

**Comment by sinni800** [comment] 2018-06-07 20:37
What would maybe help is delaying adding the loading class. When the loading is triggered, fire a timeout for a hundred or 200 miliseconds. If the video is still in the state of loading, trigger the loading class.

**Comment by sinni800** [comment] 2020-10-10 00:30
Just for an update for people having the same issue until it's officially fixed: 

In the current version, the loading spinner can be removed by a bit of style:
```
.vast_video_loading {
	display:none !important;
}
```

**Comment by HariPriyaKuberSingh** [comment] 2021-11-10 11:20
@sinni800  - Can you confirm if you could still reproduce the same issue and require an enhancement in the fluid player ?

**Comment by sinni800** [comment] 2021-11-10 19:58
@HariPriyaKuberSingh Yes, this issue is still present, We would like a loading spinner, but this way we can't have it since it still flickers the loading spinner for a single frame.

**Comment by HariPriyaKuberSingh** [comment] 2021-11-30 12:27
@sinni800 - thanks for the confirmation.The issue is being looked into and I will update the comments based on the progress. Thank you

**Comment by sinni800** [comment] 2021-11-30 13:05
@HariPriyaKuberSingh thank you for looking into it. It would be great if we could give our users with slower internet connections a loading indicator again.

**Comment by HariPriyaKuberSingh** [comment] 2022-07-12 11:20
@sinni800  - we have a fix for this in production now. can you please confirm if the issue is resolved?

**Comment by HariPriyaKuberSingh** [comment] 2022-09-19 13:12
moving the issue to closed since there is no response from the reporter

**Closed by HariPriyaKuberSingh** 2022-09-19 13:12 UTC
Labels: enhancement
