### ISSUE TITLE
Fullscreen issue with InternetExplorer

### ISSUE THREAD

**Issue by amritsingh22** [fluid-player/fluid-player#493] opened 2020-07-09 21:26 UTC
**Describe the bug**
There are three issues with fullscreen:
1. The f keyboard control does not work in Internet Explorer.
2. You can not go fullscreen even if you click on fullscreen button in bottom right. The screen just goes black. (Internet Explorer)
3. If you go fullscreen and **hit Escape on keyboard**, the fullscreen icon does not change back.

**To Reproduce**
Follow steps listed in the description.

**Expected behavior**
1. The fullscreen feature and the f keyboard control should work properly in Internet Explorer.
2. Hitting escape on keyboard when in fullscreen mode should exit fullscreen and **change back the fullscreen icon properly**

**Screenshots or Links**
![image](https://user-images.githubusercontent.com/68084500/87092181-d9953400-c1ef-11ea-8efc-ac488eec4139.png)

**Affected version**
v3.0.0

UPDATE:
Issue 1 & 2 exist in Internet explorer 11, Issue 3 exists in all browsers(Internet Explorer 11, Chrome, Edge). The issues can be experienced with the video on the fluidplayer website:

https://www.fluidplayer.com/#demo

Internet Explorer version : 11.900.18362.0

**Comment by Addvilz** [comment] 2020-07-09 21:32
Please provide version. Anything but IE 11 or latest Edge is not supported.

**Comment by amritsingh22** [comment] 2020-07-09 21:43
Issue 1 & 2 exist in Internet explorer 11, Issue 3 exists in all browsers(Internet Explorer 11, Chrome, Edge).

Internet Explorer version : 11.900.18362.0

**Comment by HariPriyaKuberSingh** [comment] 2021-11-30 13:17
@amritsingh22 - Can you please confirm if the issue is persisting or is resolved

**Comment by HariPriyaKuberSingh** [comment] 2021-12-24 10:31
@amritsingh22 - Can you please confirm if the issue is persisting or is resolved

**Comment by amritsingh22** [comment] 2021-12-24 16:29
I was able to figure out a solution. Thank you

**Comment by HariPriyaKuberSingh** [comment] 2022-01-18 09:40
Based on the reporters comment, the issue is fixed and hence closing the ticket

**Closed by HariPriyaKuberSingh** 2022-01-18 09:40 UTC
Labels: bug, needs triage
