### ISSUE TITLE
Control bar does not hide when browser preventsvideo from autoplaying

### ISSUE THREAD

**Issue by biancotv** [fluid-player/fluid-player#611] opened 2021-11-16 20:20 UTC
**Describe the bug**
The control bar does not close when a video does not autoplay. It works however when a video autoplays.

**To Reproduce**
Example: https://vid.surf/video/T272J (make sure the video does not autoplay)

**Expected behavior**
The control bar should hide after a few seconds

**Screenshots or Links**
https://vid.surf/video/T272J (Example, make sure the video does not autoplay)

**Desktop (please complete the following information if relevant):**
 - OS: Windows 10
 - Browser Chrome, Firefox

**Affected version**
v3.0.0

**Additional context**
When you click on another video on the site then the player is reloaded and control bar hides as expected

**Comment by Joel2B** [comment] 2021-11-17 05:34
you can add the fade_out class to the bar at 
https://github.com/fluid-player/fluid-player/blob/master/src/fluidplayer.js#L641
so that it is always hidden at startup

**Comment by biancotv** [comment] 2021-11-20 13:27
Thank you for your help!

I made the change in https://vid.surf/fluidhacked.js, however now when a video does not autoplay it won't display the controlbar even while hovering over the video. It is only displayed when the video is paused.

On every subsequent video I click it works flawlessly.

I made a small video demonstrating this issue: https://vid.surf/video/TUFR2

**Comment by Joel2B** [comment] 2021-11-22 02:29
since you don't use fluidplayer anymore, I can't see what happens exactly,

another thing, the autoplay only works when you have already interacted with the page, 
otherwise it will not work the first time and anything can happen.

you can mute the video before the "play()" method and see how it behaves.

**Comment by leroybm** [comment] 2023-09-06 14:28
@biancotv I could not reproduce this, is it still an issue?

**Comment by sergiomcsousa** [comment] 2024-02-26 10:34
@biancotv Is this still and issue? Can I close this? Thank you!

**Closed** 2024-02-27 15:30 UTC
Labels: bug, needs triage
