### ISSUE TITLE
skipoffset

### ISSUE THREAD

**Issue by biguz** [fluid-player/fluid-player#767] opened 2023-09-18 18:35 UTC
I found alot of errors in logs
Cannot read properties of null (reading 'skipoffset')\n    at e.decreaseSkipOffset

**Comment by biguz** [comment] 2023-09-27 08:10
Is api function skipTo not working with same issue?

**Comment by sergiomcsousa** [comment] 2024-02-28 11:47
An internal ticket was created to take care of this issue. Thank you!

**Comment by ZentoDH** [comment] 2024-07-03 10:10
Hi @biguz Could you reproduce the bug in an online editor and share it with us? We can't seem to replicate it on our end. Thank you!

**Comment by sergiomcsousa** [comment] 2024-08-01 14:07
@biguz does the problem persist? We still haven't created the internal ticket since we are waiting for the extra info from your side. Thank you!

**Comment by biguz** [comment] 2024-08-02 02:28
Sorry, can't track javascript console output right now, you can track it at cdn side

**Comment by sergiomcsousa** [comment] 2024-09-30 10:10
@ZentoDH Can you please check here what actions are necessary?

**Comment by ZentoDH** [comment] 2024-10-01 07:34
There's a ticket about this in our backlog. No action needed at this time.

**Comment by sergiomcsousa** [comment] 2024-11-13 11:17
During the investigation of this ticket we found that this issue was not reproducible. Also to confirm the github ticket created by the user was not able to give some steps to replicate this issue. Hence we are closing this ticket. @biguz

**Closed by sergiomcsousa** 2024-11-13 11:17 UTC
Labels: bug, need more info
