### ISSUE TITLE
Why hls stream not playing if browser page started first ?

### ISSUE THREAD

**Issue by gaamaaresosa** [fluid-player/fluid-player#720] opened 2023-03-29 20:35 UTC
I use fluidPlayer on my Python Flash web page.

If I start the hls stream first and wait till m3u8 and ts files are created,
then I see the preview on the fluidPlayer  well.

But on my project to save the CPU usage I start the hls stream only when then user needs the preview page.
Now I set the URL like below and show the fluidPlayer player page and waiting...

I see nothing by the buffering circle animation for long time even after m3u8 and ts files are created.
I expect the fluidPlayer player should start playing just after m3u8 and ts files are created.
But its not.

What I am missing and how to make it work for my work flow ?

```
<video id="video-id" controls>
    <source src="http://127.0.0.1/hls/play.m3u8" type='application/x-mpegURL' />
</video>
```

```
<script>
   fluidPlayer(
       'video-id',
       {
           layoutControls: {
               primaryColor:           false,
               playButtonShowing:      true,
               playPauseAnimation:     true,
               fillToContainer:        true,
               autoPlay:               false, //true,
               mute:                   false,
               keyboardControl:        false,
               layout:                 'browser', // Default 'default' or 'browser'
               allowDownload:          false,
               playbackRateEnabled:    false,            
               allowTheatre:           false,  
               //playButtonShowing:      true, // Default true
               
               controlBar: {
                   autoHide:           true,
                   autoHideTimeout:    1,
                   animated:           true
               },             
           
               playerInitCallback:     (function() {})
           }
       }
   );
</script>
```
![image](https://user-images.githubusercontent.com/21296884/228656506-2f7a4c94-a8c2-440e-9fec-5bc4deabcbff.png)

Please help me and thanks in advance.

**Comment by leroybm** [comment] 2023-09-06 10:35
@gaamaaresosa Can you reproduce this issue in a codepen for us to test? If you want to check if the problem is with `hls.js` you can try running it here https://hlsjs.video-dev.org/demo/

**Comment by sergiomcsousa** [comment] 2024-02-26 11:19
@gaamaaresosa is this still and issue? Can I close this ticket? Thank you!

**Closed** 2024-02-27 15:33 UTC
Labels: question, needs triage
