### ISSUE TITLE
[Error] (204): Timeout error. Failed to play video

### ISSUE THREAD

**Issue by mywebnote** [fluid-player/fluid-player#324] opened 2019-03-27 03:50 UTC
Hi,
I am getting [Error] (204): Timeout error. Failed to play video in every browser.
Actually I am using MPD and DASH URL'S
Did I missed something? Please help.
Here is the sample URL https://dev.vehiclevisuals.com/fluid.html

Thanks,
Pradeep

**Comment by JKusber** [comment] 2019-04-02 22:45
I have the same problem. But it is not save to reproduce the problem in my case. Did you find a solution?

**Comment by majamee** [comment] 2019-07-23 09:24
Seems to be a wide-spread issue by now. Even on the official page it throws the same error:
https://docs.fluidplayer.com/streaming/

**Comment by bharath-exads** [comment] 2019-07-23 09:41
Hi,

Thanks for letting us know
The issue occurred after DashJS updated their API
we have worked to solve this and PR #348 will be merged anytime soon

**Comment by majamee** [comment] 2019-07-23 13:28
@bharath-exads Awesome! Back to working state :)

**Comment by bharath-exads** [comment] 2019-07-23 13:43
@majamee 
Thanks so much for letting us know :)

**Closed by bharath-exads** 2019-07-23 13:43 UTC
Labels: bug

**Comment by majamee** [comment] 2019-07-31 20:14
@bharath-exads The issue seems to be back unfortunately:
https://docs.fluidplayer.com/streaming/

Tested in Chrome right now.

**Comment by bharath-exads** [comment] 2019-08-01 17:13
@majamee

**Comment by majamee** [comment] 2019-08-01 18:16
@bharath-exads Everything back to working state :)

**Comment by tranthanhtuan269** [comment] 2020-03-22 13:29
I have the same problem. How to fix it?

**Comment by tranthanhtuan269** [comment] 2020-03-22 13:30
fluid-player can't play in mobile. Please check it!!

My web is https://xemphimhot.net

**Comment by Addvilz** [comment] 2020-03-23 05:00
@tranthanhtuan269 please open a new issue and include details such as mobile device and sample code to reproduce.
